### ISSUE TITLE
How to get the IP address of the client?

### ISSUE THREAD

**Issue by jiangxuelei** [airlift/drift#109]
I think ServerInvokeRequest should be extended. For example, add a ChannelHandlerContext field?

**Comment by electrum** [comment]
We probably want to expose context object similar to how `@ThriftHeader` is used. The API for this is tricky since the context is inherently transport specific.

For example, address could be done like this:
```java
@ThriftMethod
void test(@ThriftContext("clientAddress") HostAndPort address);
```

I see a few options for the type of the context object:

* Use a specific type like `HostAndPort` which is transport specific. The user is required to pick the right type for the bound transport. (probably fine since we only have one real transport type)
* Use `String` for everything. Has obvious downsides for complex objects (like TLS information).
* Use specific types, but also allow conversion to `String`.

**Comment by jiangxuelei** [comment]
Thank for reply. Version 1.18 can solve this problem?

**Comment by electrum** [comment]
No, it’s not implemented yet.
