### ISSUE TITLE
ConnectionPool cachedConnections::cleanUp? Why?

### ISSUE THREAD

**Issue by juaby** [airlift/drift#89]
```
maintenanceThread.scheduleWithFixedDelay(cachedConnections::cleanUp, 1, 1, TimeUnit.SECONDS);
```
```
I can't understand the comments...

/**
   * Performs any pending maintenance operations needed by the cache. Exactly which activities are
   * performed -- if any -- is implementation-dependent.
   */
  void cleanUp();
```

**Comment by electrum** [comment]
The connection pool is implementing using a [Guava Cache](https://github.com/google/guava/wiki/CachesExplained).

We configure the maximum connections by setting `maximumSize()`, use `expireAfterAccess()` to implement the idle timeout (evict connections that haven't been used for a while), and add a removal listener to close any connections that are removed from the cache due to being "expired" (max size or last access).

This all works as long as connection pool is actively used. Guava Cache will perform periodic cleanup of expired entries during [writes or reads](https://github.com/google/guava/wiki/CachesExplained#when-does-cleanup-happen). However, if the traffic is bursty and the system goes idle for a while, the connections would sit in the cache longer than they should. Thus, we follow the recommendation from Guava:

>  If your cache does writes only rarely and you don't want cleanup to block cache reads, you may wish to create your own maintenance thread that calls `Cache.cleanUp()` at regular intervals. If you want to schedule regular cache maintenance for a cache which only rarely has writes, just schedule the maintenance using `ScheduledExecutorService`.

**Comment by electrum** [comment]
To more directly answer your question, the `Cache.cleanUp()` method will go through the entire cache and remove any items that are expired (and call the removal listener for those).

**Comment by juaby** [comment]
@electrum ths, 祝您好运
